2019-06-01 13:11:11.105439: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-01 13:11:11.969644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:03:00.0
totalMemory: 10.73GiB freeMemory: 10.53GiB
2019-06-01 13:11:11.969686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-01 13:11:12.631502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-01 13:11:12.631548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-06-01 13:11:12.631560: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-06-01 13:11:12.632978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10168 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:03:00.0, compute capability: 7.5)
2019-06-01 13:26:27.886167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-01 13:26:27.886250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-01 13:26:27.886279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-06-01 13:26:27.886295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-06-01 13:26:27.886999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10168 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:03:00.0, compute capability: 7.5)
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value varkeys_1/keys
	 [[{{node varkeys_1/keys/_0}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4_varkeys_1/keys", _device="/job:localhost/replica:0/task:0/device:GPU:0"](varkeys_1/keys)]]
	 [[{{node varkeys_1/keys/_1}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4_varkeys_1/keys", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MANN_vary_numberofkeys.py", line 176, in <module>
    results = fit_evaluate(model1, x_train_, y_train_, x_test, y_test, batch_size, epochs, lr)
  File "MANN_vary_numberofkeys.py", line 139, in fit_evaluate
    memory = tf.Session().run(memory)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value varkeys_1/keys
	 [[{{node varkeys_1/keys/_0}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4_varkeys_1/keys", _device="/job:localhost/replica:0/task:0/device:GPU:0"](varkeys_1/keys)]]
	 [[{{node varkeys_1/keys/_1}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4_varkeys_1/keys", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
srun: error: gpu-015: task 0: Exited with exit code 1
