2019-06-01 13:40:38.076441: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-01 13:40:38.101068: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2019-06-01 13:40:38.101210: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: gpu-017
2019-06-01 13:40:38.101279: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: gpu-017
2019-06-01 13:40:38.101395: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.79.0
2019-06-01 13:40:38.101520: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.79.0
2019-06-01 13:40:38.101592: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.79.0
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value varkeys_1/keys
	 [[{{node _retval_varkeys_1/keys_0_0}} = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](varkeys_1/keys)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MANN_vary_numberofkeys.py", line 176, in <module>
    results = fit_evaluate(model1, x_train_, y_train_, x_test, y_test, batch_size, epochs, lr)
  File "MANN_vary_numberofkeys.py", line 139, in fit_evaluate
    memory = tf.Session().run(memory)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/schestag/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value varkeys_1/keys
	 [[{{node _retval_varkeys_1/keys_0_0}} = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](varkeys_1/keys)]]
srun: error: gpu-017: task 0: Exited with exit code 1
